png('~/iCare/plots/allMAllMainPY1_predictConstPY.png',width=1200,height=800)
par(mfrow=c(2,2))
den1<-density(predObj$predictedYPerSweep[,1])
den2<-density(predObj$predictedYPerSweep[,2])
den3<-density(predObj$predictedYPerSweep[,1]-predObj$predictedYPerSweep[,2])
hist(predObj$predictedYPerSweep[,1],breaks=seq(0,1,0.01),col='blue',main='Density of risk, low intensity, high duration (A)',xlab='Risk',ylab='Density',prob=T)
lines(den1$x,den1$y,col='red',lwd=2)
hist(predObj$predictedYPerSweep[,2],breaks=seq(0,1,0.01),col='blue',main='Density of risk, high intensity, low duration (B)',xlab='Risk',ylab='Density',prob=T)
lines(den2$x,den2$y,col='red',lwd=2)
hist(predObj$predictedYPerSweep[,1]-predObj$predictedYPerSweep[,2],breaks=seq(-1,1,0.01),col='blue',main='Density of difference in risk (A-B)',xlab='Difference',ylab='Density',prob=T)
lines(den3$x,den3$y,col='red',lwd=2)
plot(sort(predObj$predictedYPerSweep[,1]),sort(predObj$predictedYPerSweep[,2]),xlim=c(0.0,1.0),ylim=c(0.0,1.0),main='QQPlot of risk for two scenarios',xlab='Risk: Low intensity, high duration',ylab='Risk: High intensity, low duration',col='blue')
abline(a=0,b=1,col='red',lwd=2)
dev.off()
png('~/iCare/plots/allMAllMainPY1_predictConstCSI.png',width=1200,height=800)
par(mfrow=c(2,2))
den1<-density(predObj$predictedYPerSweep[,3])
den2<-density(predObj$predictedYPerSweep[,4])
den3<-density(predObj$predictedYPerSweep[,3]-predObj$predictedYPerSweep[,4])
hist(predObj$predictedYPerSweep[,3],breaks=seq(0,1,0.01),col='blue',main='Density of risk, low intensity, high duration (A)',xlab='Risk',ylab='Density',prob=T)
lines(den1$x,den1$y,col='red',lwd=2)
hist(predObj$predictedYPerSweep[,4],breaks=seq(0,1,0.01),col='blue',main='Density of risk, high intensity, low duration (B)',xlab='Risk',ylab='Density',prob=T)
lines(den2$x,den2$y,col='red',lwd=2)
hist(predObj$predictedYPerSweep[,3]-predObj$predictedYPerSweep[,4],breaks=seq(-1,1,0.01),col='blue',main='Density of difference in risk (A-B)',xlab='Difference',ylab='Density',prob=T)
lines(den3$x,den3$y,col='red',lwd=2)
plot(sort(predObj$predictedYPerSweep[,3]),sort(predObj$predictedYPerSweep[,4]),xlim=c(0.0,1.0),ylim=c(0.0,1.0),main='QQPlot of risk for two scenarios',xlab='Risk: Low intensity, high duration',ylab='Risk: High intensity, low duration',col='blue')
abline(a=0,b=1,col='red',lwd=2)
dev.off()
z<-matrix(apply(predObj$predictedYPerSweep[,5:20],2,mean),nrow=4,byrow=T)
png('~/iCare/plots/allMAllMainPY1_predictGrid.png',width=1200,height=800)
image(x=1:4,y=1:4,z,col=gray((0:99)/99),zlim=c(0,1),xlab='Intensity',ylab='Duration')
dev.off()

